Added Respresso to README.md
mbiesiad/awesome-translations pull request #24
Opened 2021-05-25 10:29 UTC by jozsefmezei

To clarify:
- I'm one of the developers from the Respresso team.
- Respresso is a commercial project, but it is currently free, without ads or limitations. 
- In the future, we'll have an always-free tier for small projects. (As far as I can tell, without feature limitations, only quantity limits.)
- Respresso is not a translation only tool, it is a collaborative resource editor supporting multiple platforms, including localizations and their translations.

Most of the business logic is provided by the backend, our clients are “build-time” file downloader tools for automation.

2021-05-27 16:53 UTC, mbiesiad requested changes
Please, just change a little bit description for ~something like (quick example):

[Respresso](https://respresso.io/) - An online editor to edit resource files (localizations and translations, images, colors, etc.), a platform-specific format, automatically delivered to source code.

2021-05-27 16:53 UTC, mbiesiad commented on README.md
> +- [Respresso](https://respresso.io/) - Let your whole team edit resource files (localizations and translations, images, colors, etc.) with Respresso’s online editor to get them in a platform-specific
Description should be definition styled (please, take a look for examples above).

2021-05-27 16:57 UTC, mbiesiad commented
Hi, awesome! 🎉✨ Please just change a little bit mentioned description.

Best wishes,

2021-05-28 12:17 UTC, jozsefmezei commented
Hi mbiesiad,

Ok, I updated the description.

All the best,

2021-05-28 12:17 UTC, merged

2021-05-28 12:33 UTC, mbiesiad commented
Hi @jozsefmezei 

Awesome 🦄 many thanks! 🚀 

Best wishes,