Removed broken links
mbiesiad/awesome-translations pull request #50
Opened 2023-03-06 17:23 UTC by alexture

I removed broken links + the table of contents (since I'm planning on changing the structure very soon). This should be a pretty straightforward pull, the next one will be bigger! :)

2023-03-07 00:16 UTC, mbiesiad requested changes
Agree about err 404 and 500, great work! But I suppose that internal links are useful, until we don't have new structure, it's correct IMO

2023-03-07 00:16 UTC, mbiesiad commented on README.md
> -- [Between Translations](http://foxdocs.biz/BetweenTranslations/) - Run by Jayne Fox, a German into English translator. It talks about continuing professional development (CPD) for translators and th
Nice job! Error 500 at this moment there

2023-03-07 00:16 UTC, mbiesiad commented on README.md
> -- [Electronjs i18n](https://www.electronjs.org/apps/i18n-manager) - I18n manager for Windows.
Agree, error 404 now there - well done!

2023-03-07 00:16 UTC, mbiesiad commented on README.md
> -## Contents
I suppose we should leave this now (yet), that's valid, correct internal links :P

2023-03-07 00:20 UTC, mbiesiad commented
Hi @alexture Once again, thanks so much! In general I'm with you, agree about provided changes, but before we make new structure, in my opinion we should have ToC with internal links - many people are using these resources day after day. Thank you for understanding, best wishes

2023-03-19 12:15 UTC, alexture commented
Hi! I _think_ I fixed this but am still trying to figure out GitHub. Hopefully my latest commit added back the table of contents and still had the broken links removed :)

2023-03-24 14:06 UTC, merged

2023-03-24 14:37 UTC, mbiesiad commented
Hi. All is fine, merged. 🎉 Thanks a lot! ✨