French branch
mbiesiad/awesome-translations pull request #53
Opened 2023-08-30 14:51 UTC by alexture

Not sure if I'm supposed to do this? Also, it doesn't include the changes from my English version pull request.

2023-08-31 18:57 UTC, mbiesiad requested changes
Changes needed

2023-08-31 18:57 UTC, mbiesiad commented on README.md
> -- [Italian](https://github.com/niedev/awesome-translations/tree/it_IT)
One of the solution could be to add as 25 line - [French](https://github.com/alexture/awesome-translations/blob/fr_FR/README.md) and undo other changes in this file (as main file, should be in English).

2023-08-31 18:57 UTC, mbiesiad commented on README.md
> -- [Italian](https://github.com/niedev/awesome-translations/tree/it_IT)
`- [French](https://github.com/alexture/awesome-translations/blob/fr_FR/README.md)`

2023-09-01 06:54 UTC, alexture commented
Ohhh got it, sorry for getting this wrong!

2023-09-01 06:54 UTC, closed without merging